<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.2 on win32)" generated="20200821 13:44:36.855" rpa="false">
<suite id="s1" name="Aibpage" source="C:\Users\pegAsus\workspace_python\SeleniumTrails\WebSiteTesting\tests\aibpage.robot">
<test id="s1-t1" name="Site accessibility">
<kw name="Start" library="params" type="setup">
<arguments>
<arg>${BROWSER}</arg>
<arg>${URL}</arg>
</arguments>
<kw name="Run Keyword If" library="BuiltIn">
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<arguments>
<arg>"${BROWSER}" == "HeadlessChrome"</arg>
<arg>HeadlessChrome</arg>
<arg>ELSE</arg>
<arg>driver</arg>
<arg>${BROWSER}</arg>
</arguments>
<kw name="HeadlessChrome" library="params">
<kw name="Evaluate" library="BuiltIn">
<doc>Evaluates the given expression in Python and returns the result.</doc>
<arguments>
<arg>sys.modules['selenium.webdriver'].ChromeOptions()</arg>
<arg>sys, selenium.webdriver</arg>
</arguments>
<assign>
<var>${chromeOptions}</var>
</assign>
<msg timestamp="20200821 13:44:37.075" level="INFO">${chromeOptions} = &lt;selenium.webdriver.chrome.options.Options object at 0x00000217870A9250&gt;</msg>
<status status="PASS" starttime="20200821 13:44:37.075" endtime="20200821 13:44:37.075"></status>
</kw>
<kw name="Call Method" library="BuiltIn">
<doc>Calls the named method of the given object with the provided arguments.</doc>
<arguments>
<arg>${chrome_options}</arg>
<arg>add_argument</arg>
<arg>headless</arg>
</arguments>
<status status="PASS" starttime="20200821 13:44:37.075" endtime="20200821 13:44:37.075"></status>
</kw>
<kw name="Call Method" library="BuiltIn">
<doc>Calls the named method of the given object with the provided arguments.</doc>
<arguments>
<arg>${chrome_options}</arg>
<arg>add_argument</arg>
<arg>disable-gpu</arg>
</arguments>
<status status="PASS" starttime="20200821 13:44:37.075" endtime="20200821 13:44:37.075"></status>
</kw>
<kw name="Call Method" library="BuiltIn">
<doc>Calls the named method of the given object with the provided arguments.</doc>
<arguments>
<arg>${chrome_options}</arg>
<arg>to_capabilities</arg>
</arguments>
<assign>
<var>${options}</var>
</assign>
<msg timestamp="20200821 13:44:37.076" level="INFO">${options} = {'browserName': 'chrome', 'version': '', 'platform': 'ANY', 'goog:chromeOptions': {'extensions': [], 'args': ['headless', 'disable-gpu']}}</msg>
<status status="PASS" starttime="20200821 13:44:37.076" endtime="20200821 13:44:37.076"></status>
</kw>
<kw name="Create Webdriver" library="SeleniumLibrary">
<doc>Creates an instance of Selenium WebDriver.</doc>
<arguments>
<arg>Remote</arg>
<arg>command_executor=http://helloworld.com:4444/wd/hub</arg>
<arg>desired_capabilities=${options}</arg>
</arguments>
<msg timestamp="20200821 13:44:37.076" level="INFO">Creating an instance of the Remote WebDriver.</msg>
<msg timestamp="20200821 13:44:38.165" level="INFO">Could not connect to port 4444 on host helloworld.com</msg>
<msg timestamp="20200821 13:44:38.165" level="INFO">Could not get IP address for host: helloworld.com</msg>
<msg timestamp="20200821 13:44:59.204" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D6100&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /wd/hub/session</msg>
<msg timestamp="20200821 13:45:20.333" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D6250&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /wd/hub/session</msg>
<msg timestamp="20200821 13:45:41.440" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D63D0&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20200821 13:46:02.557" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20200821 13:46:02.556" endtime="20200821 13:46:02.557"></status>
</kw>
<msg timestamp="20200821 13:46:02.560" level="FAIL">MaxRetryError: HTTPConnectionPool(host='helloworld.com', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D6520&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))</msg>
<status status="FAIL" starttime="20200821 13:44:37.076" endtime="20200821 13:46:02.560"></status>
</kw>
<status status="FAIL" starttime="20200821 13:44:37.074" endtime="20200821 13:46:02.561"></status>
</kw>
<status status="FAIL" starttime="20200821 13:44:37.074" endtime="20200821 13:46:02.561"></status>
</kw>
<status status="FAIL" starttime="20200821 13:44:37.074" endtime="20200821 13:46:02.561"></status>
</kw>
<kw name="Stop" library="params" type="teardown">
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20200821 13:46:02.562" endtime="20200821 13:46:02.562"></status>
</kw>
<status status="PASS" starttime="20200821 13:46:02.561" endtime="20200821 13:46:02.562"></status>
</kw>
<doc>site accessibility test</doc>
<tags>
<tag>Smoke</tag>
</tags>
<status status="FAIL" starttime="20200821 13:44:37.073" endtime="20200821 13:46:02.563" critical="yes">Setup failed:
MaxRetryError: HTTPConnectionPool(host='helloworld.com', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D6520&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))</status>
</test>
<status status="FAIL" starttime="20200821 13:44:36.857" endtime="20200821 13:46:02.566"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">Smoke</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Aibpage">Aibpage</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200821 13:44:59.204" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D6100&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /wd/hub/session</msg>
<msg timestamp="20200821 13:45:20.333" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D6250&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /wd/hub/session</msg>
<msg timestamp="20200821 13:45:41.440" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x00000217870D63D0&gt;: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /wd/hub/session</msg>
</errors>
</robot>
